// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategories = `-- name: CountCategories :one
SELECT
    COUNT(*)
FROM
    category
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO
    category
(name, last_update)
VALUES
($1, NOW())
RETURNING category_id, name, last_update
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.CategoryID, &i.Name, &i.LastUpdate)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM 
    category
WHERE category_id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryID int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, categoryID)
	return err
}

const fetchCategories = `-- name: FetchCategories :many
SELECT
    category_id, name, last_update
FROM 
    category
ORDER BY category_id ASC
LIMIT $1
OFFSET $2
`

type FetchCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchCategories(ctx context.Context, arg FetchCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, fetchCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.LastUpdate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchCategoryFilms = `-- name: FetchCategoryFilms :many
SELECT
    film.film_id, film.title, film.description, film.release_year, film.language_id, film.rental_duration, film.rental_rate, film.length, film.replacement_cost, film.rating, film.last_update, film.special_features, film.fulltext
FROM 
    film
JOIN 
    film_category 
    ON
    film_category.film_id = film.film_id
WHERE 
    film_category.category_id = $1
ORDER BY title ASC
LIMIT $2
OFFSET $3
`

type FetchCategoryFilmsParams struct {
	CategoryID int16 `json:"category_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) FetchCategoryFilms(ctx context.Context, arg FetchCategoryFilmsParams) ([]Film, error) {
	rows, err := q.db.Query(ctx, fetchCategoryFilms, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Film
	for rows.Next() {
		var i Film
		if err := rows.Scan(
			&i.FilmID,
			&i.Title,
			&i.Description,
			&i.ReleaseYear,
			&i.LanguageID,
			&i.RentalDuration,
			&i.RentalRate,
			&i.Length,
			&i.ReplacementCost,
			&i.Rating,
			&i.LastUpdate,
			&i.SpecialFeatures,
			&i.Fulltext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT
    category_id, name, last_update
FROM 
    category
WHERE category_id = $1
LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, categoryID int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, categoryID)
	var i Category
	err := row.Scan(&i.CategoryID, &i.Name, &i.LastUpdate)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE 
    category
SET 
    name = $2
WHERE category_id = $1
RETURNING category_id, name, last_update
`

type UpdateCategoryParams struct {
	CategoryID int32  `json:"category_id"`
	Name       string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.CategoryID, arg.Name)
	var i Category
	err := row.Scan(&i.CategoryID, &i.Name, &i.LastUpdate)
	return i, err
}

const updateCategoryPartial = `-- name: UpdateCategoryPartial :one
UPDATE
    category
SET
    name = COALESCE($1, name)
WHERE category_id = $2
RETURNING category_id, name, last_update
`

type UpdateCategoryPartialParams struct {
	Name       pgtype.Text `json:"name"`
	CategoryID int32       `json:"category_id"`
}

func (q *Queries) UpdateCategoryPartial(ctx context.Context, arg UpdateCategoryPartialParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategoryPartial, arg.Name, arg.CategoryID)
	var i Category
	err := row.Scan(&i.CategoryID, &i.Name, &i.LastUpdate)
	return i, err
}
