// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: city.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCities = `-- name: CountCities :one
SELECT
    COUNT(*)
FROM
    city
`

func (q *Queries) CountCities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO
    city
(country_id, city, last_update)
VALUES
($1, $2, NOW())
RETURNING city_id, city, country_id, last_update
`

type CreateCityParams struct {
	CountryID int16  `json:"country_id"`
	City      string `json:"city"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity, arg.CountryID, arg.City)
	var i City
	err := row.Scan(
		&i.CityID,
		&i.City,
		&i.CountryID,
		&i.LastUpdate,
	)
	return i, err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM 
    city
WHERE city_id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, cityID int32) error {
	_, err := q.db.Exec(ctx, deleteCity, cityID)
	return err
}

const fetchCities = `-- name: FetchCities :many
SELECT
    city_id, city, country_id, last_update
FROM 
    city
ORDER BY city_id ASC
LIMIT $1
OFFSET $2
`

type FetchCitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchCities(ctx context.Context, arg FetchCitiesParams) ([]City, error) {
	rows, err := q.db.Query(ctx, fetchCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.CityID,
			&i.City,
			&i.CountryID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCity = `-- name: GetCity :one
SELECT
    city_id, city, country_id, last_update
FROM 
    city
WHERE city_id = $1
LIMIT 1
`

func (q *Queries) GetCity(ctx context.Context, cityID int32) (City, error) {
	row := q.db.QueryRow(ctx, getCity, cityID)
	var i City
	err := row.Scan(
		&i.CityID,
		&i.City,
		&i.CountryID,
		&i.LastUpdate,
	)
	return i, err
}

const updateCity = `-- name: UpdateCity :one
UPDATE 
    city
SET 
    country_id = $2,
    city = $3
WHERE city_id = $1
RETURNING city_id, city, country_id, last_update
`

type UpdateCityParams struct {
	CityID    int32  `json:"city_id"`
	CountryID int16  `json:"country_id"`
	City      string `json:"city"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, updateCity, arg.CityID, arg.CountryID, arg.City)
	var i City
	err := row.Scan(
		&i.CityID,
		&i.City,
		&i.CountryID,
		&i.LastUpdate,
	)
	return i, err
}

const updateCityPartial = `-- name: UpdateCityPartial :one
UPDATE
    city
SET
    country_id = COALESCE($1, country_id),
    city = COALESCE($2, city)
WHERE city_id = $3
RETURNING city_id, city, country_id, last_update
`

type UpdateCityPartialParams struct {
	CountryID pgtype.Int2 `json:"country_id"`
	City      pgtype.Text `json:"city"`
	CityID    int32       `json:"city_id"`
}

func (q *Queries) UpdateCityPartial(ctx context.Context, arg UpdateCityPartialParams) (City, error) {
	row := q.db.QueryRow(ctx, updateCityPartial, arg.CountryID, arg.City, arg.CityID)
	var i City
	err := row.Scan(
		&i.CityID,
		&i.City,
		&i.CountryID,
		&i.LastUpdate,
	)
	return i, err
}
