// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT
    COUNT(*)
FROM
    customer
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customer (
    first_name,
    last_name,
    email,
    address_id,
    store_id,
    activebool,
    active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    CASE
        WHEN $6 THEN 1
        ELSE 0
    END
)
RETURNING customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active
`

type CreateCustomerParams struct {
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Email      pgtype.Text `json:"email"`
	AddressID  int16       `json:"address_id"`
	StoreID    int16       `json:"store_id"`
	Activebool bool        `json:"activebool"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AddressID,
		arg.StoreID,
		arg.Activebool,
	)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.StoreID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AddressID,
		&i.Activebool,
		&i.CreateDate,
		&i.LastUpdate,
		&i.Active,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM
    customer
WHERE
    customer_id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, customerID int32) error {
	_, err := q.db.Exec(ctx, deleteCustomer, customerID)
	return err
}

const fetchCustomerPayments = `-- name: FetchCustomerPayments :many
SELECT
    payment.payment_id, payment.customer_id, payment.staff_id, payment.rental_id, payment.amount, payment.payment_date
FROM
    payment
WHERE
    payment.customer_id = $1
ORDER BY payment_date DESC
LIMIT $2
OFFSET $3
`

type FetchCustomerPaymentsParams struct {
	CustomerID int16 `json:"customer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) FetchCustomerPayments(ctx context.Context, arg FetchCustomerPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, fetchCustomerPayments, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchCustomerRentals = `-- name: FetchCustomerRentals :many
SELECT
    rental.rental_id, rental.rental_date, rental.inventory_id, rental.customer_id, rental.return_date, rental.staff_id, rental.last_update
FROM
    rental
WHERE
    rental.customer_id = $1
ORDER BY rental_date DESC
LIMIT $2
OFFSET $3
`

type FetchCustomerRentalsParams struct {
	CustomerID int16 `json:"customer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) FetchCustomerRentals(ctx context.Context, arg FetchCustomerRentalsParams) ([]Rental, error) {
	rows, err := q.db.Query(ctx, fetchCustomerRentals, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rental
	for rows.Next() {
		var i Rental
		if err := rows.Scan(
			&i.RentalID,
			&i.RentalDate,
			&i.InventoryID,
			&i.CustomerID,
			&i.ReturnDate,
			&i.StaffID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchCustomers = `-- name: FetchCustomers :many
SELECT
    customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active
FROM
    customer
LIMIT $1
OFFSET $2
`

type FetchCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchCustomers(ctx context.Context, arg FetchCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, fetchCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustomerID,
			&i.StoreID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AddressID,
			&i.Activebool,
			&i.CreateDate,
			&i.LastUpdate,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT
    customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active
FROM
    customer
WHERE
    customer_id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, customerID int32) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, customerID)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.StoreID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AddressID,
		&i.Activebool,
		&i.CreateDate,
		&i.LastUpdate,
		&i.Active,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customer
SET
    first_name = $1,
    last_name = $2,
    email = $3,
    address_id = $4,
    store_id = $5,
    activebool = $6,
    active = CASE
        WHEN $6 THEN 1
        ELSE 0
    END,
    last_update = NOW()
WHERE
    customer_id = $7
RETURNING customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active
`

type UpdateCustomerParams struct {
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Email      pgtype.Text `json:"email"`
	AddressID  int16       `json:"address_id"`
	StoreID    int16       `json:"store_id"`
	Activebool bool        `json:"activebool"`
	CustomerID int32       `json:"customer_id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AddressID,
		arg.StoreID,
		arg.Activebool,
		arg.CustomerID,
	)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.StoreID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AddressID,
		&i.Activebool,
		&i.CreateDate,
		&i.LastUpdate,
		&i.Active,
	)
	return i, err
}

const updateCustomerPartial = `-- name: UpdateCustomerPartial :one
UPDATE customer
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    email = COALESCE($3, email),
    address_id = COALESCE($4, address_id),
    store_id = COALESCE($5, store_id),
    activebool = COALESCE($6, activebool),
    active = CASE
        WHEN $6 IS NULL THEN active
        WHEN $6 THEN 1
        ELSE 0
    END,
    last_update = NOW()
WHERE
    customer_id = $7
RETURNING customer_id, store_id, first_name, last_name, email, address_id, activebool, create_date, last_update, active
`

type UpdateCustomerPartialParams struct {
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	Email      pgtype.Text `json:"email"`
	AddressID  pgtype.Int2 `json:"address_id"`
	StoreID    pgtype.Int2 `json:"store_id"`
	Activebool pgtype.Bool `json:"activebool"`
	CustomerID int32       `json:"customer_id"`
}

func (q *Queries) UpdateCustomerPartial(ctx context.Context, arg UpdateCustomerPartialParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerPartial,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AddressID,
		arg.StoreID,
		arg.Activebool,
		arg.CustomerID,
	)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.StoreID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AddressID,
		&i.Activebool,
		&i.CreateDate,
		&i.LastUpdate,
		&i.Active,
	)
	return i, err
}
