// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: film.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilms = `-- name: CountFilms :one
SELECT
    COUNT(*)
FROM
    film
`

func (q *Queries) CountFilms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFilms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFilm = `-- name: CreateFilm :one
INSERT INTO film (
    title,
    description,
    release_year,
    language_id,
    rental_duration,
    rental_rate,
    length,
    replacement_cost,
    rating,
    special_features
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext
`

type CreateFilmParams struct {
	Title           string         `json:"title"`
	Description     pgtype.Text    `json:"description"`
	ReleaseYear     interface{}    `json:"release_year"`
	LanguageID      int16          `json:"language_id"`
	RentalDuration  int16          `json:"rental_duration"`
	RentalRate      pgtype.Numeric `json:"rental_rate"`
	Length          pgtype.Int2    `json:"length"`
	ReplacementCost pgtype.Numeric `json:"replacement_cost"`
	Rating          NullMpaaRating `json:"rating"`
	SpecialFeatures []string       `json:"special_features"`
}

func (q *Queries) CreateFilm(ctx context.Context, arg CreateFilmParams) (Film, error) {
	row := q.db.QueryRow(ctx, createFilm,
		arg.Title,
		arg.Description,
		arg.ReleaseYear,
		arg.LanguageID,
		arg.RentalDuration,
		arg.RentalRate,
		arg.Length,
		arg.ReplacementCost,
		arg.Rating,
		arg.SpecialFeatures,
	)
	var i Film
	err := row.Scan(
		&i.FilmID,
		&i.Title,
		&i.Description,
		&i.ReleaseYear,
		&i.LanguageID,
		&i.RentalDuration,
		&i.RentalRate,
		&i.Length,
		&i.ReplacementCost,
		&i.Rating,
		&i.LastUpdate,
		&i.SpecialFeatures,
		&i.Fulltext,
	)
	return i, err
}

const deleteFilm = `-- name: DeleteFilm :exec
DELETE FROM film
WHERE film_id = $1
`

func (q *Queries) DeleteFilm(ctx context.Context, filmID int32) error {
	_, err := q.db.Exec(ctx, deleteFilm, filmID)
	return err
}

const fetchFilmActors = `-- name: FetchFilmActors :many
SELECT
    actor.actor_id, actor.first_name, actor.last_name, actor.last_update
FROM 
    actor
JOIN 
    film_actor 
    ON
    film_actor.actor_id = actor.actor_id
WHERE 
    film_actor.film_id = $1
ORDER BY first_name ASC
LIMIT $2
OFFSET $3
`

type FetchFilmActorsParams struct {
	FilmID int16 `json:"film_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchFilmActors(ctx context.Context, arg FetchFilmActorsParams) ([]Actor, error) {
	rows, err := q.db.Query(ctx, fetchFilmActors, arg.FilmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ActorID,
			&i.FirstName,
			&i.LastName,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchFilmCategories = `-- name: FetchFilmCategories :many
SELECT
    category.category_id, category.name, category.last_update
FROM 
    category
JOIN 
    film_category
    ON
    film_category.category_id = category.category_id
WHERE 
    film_category.film_id = $1
ORDER BY name ASC
LIMIT $2
OFFSET $3
`

type FetchFilmCategoriesParams struct {
	FilmID int16 `json:"film_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchFilmCategories(ctx context.Context, arg FetchFilmCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, fetchFilmCategories, arg.FilmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.LastUpdate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchFilmInventory = `-- name: FetchFilmInventory :many
SELECT
    inventory.inventory_id, inventory.film_id, inventory.store_id, inventory.last_update
FROM
    inventory
WHERE
    inventory.film_id = $1
ORDER BY film_id ASC
LIMIT $2
OFFSET $3
`

type FetchFilmInventoryParams struct {
	FilmID int16 `json:"film_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchFilmInventory(ctx context.Context, arg FetchFilmInventoryParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, fetchFilmInventory, arg.FilmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.InventoryID,
			&i.FilmID,
			&i.StoreID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchFilms = `-- name: FetchFilms :many
SELECT
    film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext
FROM 
    film
ORDER BY film_id ASC
LIMIT $1
OFFSET $2
`

type FetchFilmsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchFilms(ctx context.Context, arg FetchFilmsParams) ([]Film, error) {
	rows, err := q.db.Query(ctx, fetchFilms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Film
	for rows.Next() {
		var i Film
		if err := rows.Scan(
			&i.FilmID,
			&i.Title,
			&i.Description,
			&i.ReleaseYear,
			&i.LanguageID,
			&i.RentalDuration,
			&i.RentalRate,
			&i.Length,
			&i.ReplacementCost,
			&i.Rating,
			&i.LastUpdate,
			&i.SpecialFeatures,
			&i.Fulltext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilm = `-- name: GetFilm :one
SELECT
    film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext
FROM 
    film
WHERE film_id = $1
LIMIT 1
`

func (q *Queries) GetFilm(ctx context.Context, filmID int32) (Film, error) {
	row := q.db.QueryRow(ctx, getFilm, filmID)
	var i Film
	err := row.Scan(
		&i.FilmID,
		&i.Title,
		&i.Description,
		&i.ReleaseYear,
		&i.LanguageID,
		&i.RentalDuration,
		&i.RentalRate,
		&i.Length,
		&i.ReplacementCost,
		&i.Rating,
		&i.LastUpdate,
		&i.SpecialFeatures,
		&i.Fulltext,
	)
	return i, err
}

const updateFilm = `-- name: UpdateFilm :one
UPDATE film
SET
    title = $2,
    description = $3,
    release_year = $4,
    language_id = $5,
    rental_duration = $6,
    rental_rate = $7,
    length = $8,
    replacement_cost = $9,
    rating = $10,
    special_features = $11,
    last_update = NOW()
WHERE film_id = $1
RETURNING film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext
`

type UpdateFilmParams struct {
	FilmID          int32          `json:"film_id"`
	Title           string         `json:"title"`
	Description     pgtype.Text    `json:"description"`
	ReleaseYear     interface{}    `json:"release_year"`
	LanguageID      int16          `json:"language_id"`
	RentalDuration  int16          `json:"rental_duration"`
	RentalRate      pgtype.Numeric `json:"rental_rate"`
	Length          pgtype.Int2    `json:"length"`
	ReplacementCost pgtype.Numeric `json:"replacement_cost"`
	Rating          NullMpaaRating `json:"rating"`
	SpecialFeatures []string       `json:"special_features"`
}

func (q *Queries) UpdateFilm(ctx context.Context, arg UpdateFilmParams) (Film, error) {
	row := q.db.QueryRow(ctx, updateFilm,
		arg.FilmID,
		arg.Title,
		arg.Description,
		arg.ReleaseYear,
		arg.LanguageID,
		arg.RentalDuration,
		arg.RentalRate,
		arg.Length,
		arg.ReplacementCost,
		arg.Rating,
		arg.SpecialFeatures,
	)
	var i Film
	err := row.Scan(
		&i.FilmID,
		&i.Title,
		&i.Description,
		&i.ReleaseYear,
		&i.LanguageID,
		&i.RentalDuration,
		&i.RentalRate,
		&i.Length,
		&i.ReplacementCost,
		&i.Rating,
		&i.LastUpdate,
		&i.SpecialFeatures,
		&i.Fulltext,
	)
	return i, err
}
