// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package repo

import (
	"context"
)

const countInventories = `-- name: CountInventories :one
SELECT
    COUNT(*)
FROM
    inventory
`

func (q *Queries) CountInventories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInventories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO
    inventory
(
    film_id,
    store_id,
    last_update
)
VALUES
(
    $1,
    $2,
    NOW()
)
RETURNING inventory_id, film_id, store_id, last_update
`

type CreateInventoryParams struct {
	FilmID  int16 `json:"film_id"`
	StoreID int16 `json:"store_id"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.FilmID, arg.StoreID)
	var i Inventory
	err := row.Scan(
		&i.InventoryID,
		&i.FilmID,
		&i.StoreID,
		&i.LastUpdate,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM 
    inventory
WHERE inventory_id = $1
`

func (q *Queries) DeleteInventory(ctx context.Context, inventoryID int32) error {
	_, err := q.db.Exec(ctx, deleteInventory, inventoryID)
	return err
}

const fetchInventories = `-- name: FetchInventories :many
SELECT
    inventory_id, film_id, store_id, last_update
FROM 
    inventory
LIMIT $1
OFFSET $2
`

type FetchInventoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchInventories(ctx context.Context, arg FetchInventoriesParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, fetchInventories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.InventoryID,
			&i.FilmID,
			&i.StoreID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventory = `-- name: GetInventory :one
SELECT
    inventory_id, film_id, store_id, last_update
FROM 
    inventory
WHERE inventory_id = $1
LIMIT 1
`

func (q *Queries) GetInventory(ctx context.Context, inventoryID int32) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventory, inventoryID)
	var i Inventory
	err := row.Scan(
		&i.InventoryID,
		&i.FilmID,
		&i.StoreID,
		&i.LastUpdate,
	)
	return i, err
}
