// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayments = `-- name: CountPayments :one
SELECT
    COUNT(*)
FROM
    payment
`

func (q *Queries) CountPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO
    payment
(
    customer_id,
    rental_id,
    staff_id,
    amount,
    payment_date
)
VALUES
($1, $2, $3, $4, NOW())
RETURNING payment_id, customer_id, staff_id, rental_id, amount, payment_date
`

type CreatePaymentParams struct {
	CustomerID int16          `json:"customer_id"`
	RentalID   int32          `json:"rental_id"`
	StaffID    int16          `json:"staff_id"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.CustomerID,
		arg.RentalID,
		arg.StaffID,
		arg.Amount,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.CustomerID,
		&i.StaffID,
		&i.RentalID,
		&i.Amount,
		&i.PaymentDate,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM 
    payment
WHERE payment_id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, paymentID int32) error {
	_, err := q.db.Exec(ctx, deletePayment, paymentID)
	return err
}

const fetchPayments = `-- name: FetchPayments :many
SELECT
    payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM
    payment
ORDER BY payment_id ASC
LIMIT $1
OFFSET $2
`

type FetchPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchPayments(ctx context.Context, arg FetchPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, fetchPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayment = `-- name: GetPayment :one
SELECT
    payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM 
    payment
WHERE payment_id = $1
`

func (q *Queries) GetPayment(ctx context.Context, paymentID int32) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, paymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.CustomerID,
		&i.StaffID,
		&i.RentalID,
		&i.Amount,
		&i.PaymentDate,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE 
    payment
SET
    customer_id = $2,
    rental_id = $3,
    staff_id = $4,
    amount = $5,
    payment_date = NOW()
WHERE payment_id = $1
RETURNING payment_id, customer_id, staff_id, rental_id, amount, payment_date
`

type UpdatePaymentParams struct {
	PaymentID  int32          `json:"payment_id"`
	CustomerID int16          `json:"customer_id"`
	RentalID   int32          `json:"rental_id"`
	StaffID    int16          `json:"staff_id"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.PaymentID,
		arg.CustomerID,
		arg.RentalID,
		arg.StaffID,
		arg.Amount,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.CustomerID,
		&i.StaffID,
		&i.RentalID,
		&i.Amount,
		&i.PaymentDate,
	)
	return i, err
}
