// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CountActors(ctx context.Context) (int64, error)
	CountAddresses(ctx context.Context) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountCities(ctx context.Context) (int64, error)
	CountCountries(ctx context.Context) (int64, error)
	CountCustomers(ctx context.Context) (int64, error)
	CountFilms(ctx context.Context) (int64, error)
	CountInventories(ctx context.Context) (int64, error)
	CountLanguages(ctx context.Context) (int64, error)
	CountRentals(ctx context.Context) (int64, error)
	CountStaffs(ctx context.Context) (int64, error)
	CountStores(ctx context.Context) (int64, error)
	CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	CreateCountry(ctx context.Context, country string) (Country, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	CreateRental(ctx context.Context, arg CreateRentalParams) (Rental, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	DeleteActor(ctx context.Context, actorID int32) error
	DeleteAddress(ctx context.Context, addressID int32) error
	DeleteCategory(ctx context.Context, categoryID int32) error
	DeleteCity(ctx context.Context, cityID int32) error
	DeleteCountry(ctx context.Context, countryID int32) error
	DeleteCustomer(ctx context.Context, customerID int32) error
	DeleteInventory(ctx context.Context, inventoryID int32) error
	DeleteRental(ctx context.Context, rentalID int32) error
	DeleteStaff(ctx context.Context, staffID int32) error
	DeleteStore(ctx context.Context, storeID int32) error
	FetchActorFilms(ctx context.Context, arg FetchActorFilmsParams) ([]Film, error)
	FetchActors(ctx context.Context, arg FetchActorsParams) ([]Actor, error)
	FetchAddresses(ctx context.Context, arg FetchAddressesParams) ([]Address, error)
	FetchCategories(ctx context.Context, arg FetchCategoriesParams) ([]Category, error)
	FetchCategoryFilms(ctx context.Context, arg FetchCategoryFilmsParams) ([]Film, error)
	FetchCities(ctx context.Context, arg FetchCitiesParams) ([]City, error)
	FetchCountries(ctx context.Context, arg FetchCountriesParams) ([]Country, error)
	FetchCountryCities(ctx context.Context, arg FetchCountryCitiesParams) ([]City, error)
	FetchCustomers(ctx context.Context, arg FetchCustomersParams) ([]Customer, error)
	FetchFilmActors(ctx context.Context, arg FetchFilmActorsParams) ([]Actor, error)
	FetchFilmCategories(ctx context.Context, arg FetchFilmCategoriesParams) ([]Category, error)
	FetchFilmInventory(ctx context.Context, arg FetchFilmInventoryParams) ([]Inventory, error)
	FetchFilms(ctx context.Context, arg FetchFilmsParams) ([]Film, error)
	FetchInventories(ctx context.Context, arg FetchInventoriesParams) ([]Inventory, error)
	FetchLanguages(ctx context.Context, arg FetchLanguagesParams) ([]Language, error)
	FetchRentals(ctx context.Context, arg FetchRentalsParams) ([]Rental, error)
	FetchStaffs(ctx context.Context, arg FetchStaffsParams) ([]Staff, error)
	FetchStoreCustomers(ctx context.Context, arg FetchStoreCustomersParams) ([]Customer, error)
	FetchStoreInventory(ctx context.Context, arg FetchStoreInventoryParams) ([]Inventory, error)
	FetchStores(ctx context.Context, arg FetchStoresParams) ([]Store, error)
	GetActor(ctx context.Context, actorID int32) (Actor, error)
	GetAddress(ctx context.Context, addressID int32) (Address, error)
	GetCategory(ctx context.Context, categoryID int32) (Category, error)
	GetCity(ctx context.Context, cityID int32) (City, error)
	GetCountry(ctx context.Context, countryID int32) (Country, error)
	GetCustomer(ctx context.Context, customerID int32) (Customer, error)
	GetFilm(ctx context.Context, filmID int32) (Film, error)
	GetInventory(ctx context.Context, inventoryID int32) (Inventory, error)
	GetLanguage(ctx context.Context, languageID int32) (Language, error)
	GetRental(ctx context.Context, rentalID int32) (Rental, error)
	GetStaff(ctx context.Context, staffID int32) (Staff, error)
	GetStore(ctx context.Context, storeID int32) (Store, error)
	ReturnRental(ctx context.Context, rentalID int32) (Rental, error)
	UpdateActor(ctx context.Context, arg UpdateActorParams) (Actor, error)
	UpdateActorPartial(ctx context.Context, arg UpdateActorPartialParams) (Actor, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateAddressPartial(ctx context.Context, arg UpdateAddressPartialParams) (Address, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryPartial(ctx context.Context, arg UpdateCategoryPartialParams) (Category, error)
	UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error)
	UpdateCityPartial(ctx context.Context, arg UpdateCityPartialParams) (City, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerPartial(ctx context.Context, arg UpdateCustomerPartialParams) (Customer, error)
	UpdateRental(ctx context.Context, arg UpdateRentalParams) (Rental, error)
	UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error)
	UpdateStaffPartial(ctx context.Context, arg UpdateStaffPartialParams) (Staff, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
	UpdateStorePartial(ctx context.Context, arg UpdateStorePartialParams) (Store, error)
}

var _ Querier = (*Queries)(nil)
