// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rental.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRentals = `-- name: CountRentals :one
SELECT
    COUNT(*)
FROM
    rental
`

func (q *Queries) CountRentals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRentals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRental = `-- name: CreateRental :one
INSERT INTO rental (
    rental_date,
    inventory_id,
    customer_id,
    staff_id,
    return_date
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update
`

type CreateRentalParams struct {
	RentalDate  pgtype.Timestamp `json:"rental_date"`
	InventoryID int32            `json:"inventory_id"`
	CustomerID  int16            `json:"customer_id"`
	StaffID     int16            `json:"staff_id"`
	ReturnDate  pgtype.Timestamp `json:"return_date"`
}

func (q *Queries) CreateRental(ctx context.Context, arg CreateRentalParams) (Rental, error) {
	row := q.db.QueryRow(ctx, createRental,
		arg.RentalDate,
		arg.InventoryID,
		arg.CustomerID,
		arg.StaffID,
		arg.ReturnDate,
	)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.RentalDate,
		&i.InventoryID,
		&i.CustomerID,
		&i.ReturnDate,
		&i.StaffID,
		&i.LastUpdate,
	)
	return i, err
}

const deleteRental = `-- name: DeleteRental :exec
DELETE FROM
    rental
WHERE
    rental_id = $1
`

func (q *Queries) DeleteRental(ctx context.Context, rentalID int32) error {
	_, err := q.db.Exec(ctx, deleteRental, rentalID)
	return err
}

const fetchRentals = `-- name: FetchRentals :many
SELECT
    rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update
FROM
    rental
LIMIT $1
OFFSET $2
`

type FetchRentalsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchRentals(ctx context.Context, arg FetchRentalsParams) ([]Rental, error) {
	rows, err := q.db.Query(ctx, fetchRentals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rental
	for rows.Next() {
		var i Rental
		if err := rows.Scan(
			&i.RentalID,
			&i.RentalDate,
			&i.InventoryID,
			&i.CustomerID,
			&i.ReturnDate,
			&i.StaffID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRental = `-- name: GetRental :one
SELECT
    rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update
FROM
    rental
WHERE
    rental_id = $1
LIMIT 1
`

func (q *Queries) GetRental(ctx context.Context, rentalID int32) (Rental, error) {
	row := q.db.QueryRow(ctx, getRental, rentalID)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.RentalDate,
		&i.InventoryID,
		&i.CustomerID,
		&i.ReturnDate,
		&i.StaffID,
		&i.LastUpdate,
	)
	return i, err
}

const returnRental = `-- name: ReturnRental :one
UPDATE
    rental
SET
    return_date = NOW(),
    last_update = NOW()
WHERE
    rental_id = $1
RETURNING rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update
`

func (q *Queries) ReturnRental(ctx context.Context, rentalID int32) (Rental, error) {
	row := q.db.QueryRow(ctx, returnRental, rentalID)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.RentalDate,
		&i.InventoryID,
		&i.CustomerID,
		&i.ReturnDate,
		&i.StaffID,
		&i.LastUpdate,
	)
	return i, err
}

const updateRental = `-- name: UpdateRental :one
UPDATE
    rental
SET
    rental_date = $2,
    inventory_id = $3,
    customer_id = $4,
    staff_id = $5,
    return_date = $6,
    last_update = NOW()
WHERE
    rental_id = $1
RETURNING rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update
`

type UpdateRentalParams struct {
	RentalID    int32            `json:"rental_id"`
	RentalDate  pgtype.Timestamp `json:"rental_date"`
	InventoryID int32            `json:"inventory_id"`
	CustomerID  int16            `json:"customer_id"`
	StaffID     int16            `json:"staff_id"`
	ReturnDate  pgtype.Timestamp `json:"return_date"`
}

func (q *Queries) UpdateRental(ctx context.Context, arg UpdateRentalParams) (Rental, error) {
	row := q.db.QueryRow(ctx, updateRental,
		arg.RentalID,
		arg.RentalDate,
		arg.InventoryID,
		arg.CustomerID,
		arg.StaffID,
		arg.ReturnDate,
	)
	var i Rental
	err := row.Scan(
		&i.RentalID,
		&i.RentalDate,
		&i.InventoryID,
		&i.CustomerID,
		&i.ReturnDate,
		&i.StaffID,
		&i.LastUpdate,
	)
	return i, err
}
