// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStaffs = `-- name: CountStaffs :one
SELECT
    COUNT(*)
FROM
    staff
`

func (q *Queries) CountStaffs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaffs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO
    staff
(
    first_name,
    last_name,
    email, 
    address_id,
    store_id,
    active, 
    username,
    password, 
    picture,
    last_update
)
VALUES
(
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
RETURNING staff_id, first_name, last_name, address_id, email, store_id, active, username, password, last_update, picture
`

type CreateStaffParams struct {
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     pgtype.Text `json:"email"`
	AddressID int16       `json:"address_id"`
	StoreID   int16       `json:"store_id"`
	Active    bool        `json:"active"`
	Username  string      `json:"username"`
	Password  pgtype.Text `json:"password"`
	Picture   []byte      `json:"picture"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AddressID,
		arg.StoreID,
		arg.Active,
		arg.Username,
		arg.Password,
		arg.Picture,
	)
	var i Staff
	err := row.Scan(
		&i.StaffID,
		&i.FirstName,
		&i.LastName,
		&i.AddressID,
		&i.Email,
		&i.StoreID,
		&i.Active,
		&i.Username,
		&i.Password,
		&i.LastUpdate,
		&i.Picture,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM
    staff
WHERE staff_id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, staffID int32) error {
	_, err := q.db.Exec(ctx, deleteStaff, staffID)
	return err
}

const fetchStaffPayments = `-- name: FetchStaffPayments :many
SELECT
    payment.payment_id, payment.customer_id, payment.staff_id, payment.rental_id, payment.amount, payment.payment_date
FROM
    payment
WHERE
    payment.staff_id = $1
ORDER BY payment_date DESC
LIMIT $2
OFFSET $3
`

type FetchStaffPaymentsParams struct {
	StaffID int16 `json:"staff_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) FetchStaffPayments(ctx context.Context, arg FetchStaffPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, fetchStaffPayments, arg.StaffID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchStaffRentals = `-- name: FetchStaffRentals :many
SELECT
    rental.rental_id, rental.rental_date, rental.inventory_id, rental.customer_id, rental.return_date, rental.staff_id, rental.last_update
FROM
    rental
WHERE
    rental.staff_id = $1
ORDER BY rental_date DESC
LIMIT $2
OFFSET $3
`

type FetchStaffRentalsParams struct {
	StaffID int16 `json:"staff_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) FetchStaffRentals(ctx context.Context, arg FetchStaffRentalsParams) ([]Rental, error) {
	rows, err := q.db.Query(ctx, fetchStaffRentals, arg.StaffID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rental
	for rows.Next() {
		var i Rental
		if err := rows.Scan(
			&i.RentalID,
			&i.RentalDate,
			&i.InventoryID,
			&i.CustomerID,
			&i.ReturnDate,
			&i.StaffID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchStaffs = `-- name: FetchStaffs :many
SELECT
    staff_id, first_name, last_name, address_id, email, store_id, active, username, password, last_update, picture
FROM
    staff
LIMIT $1
OFFSET $2
`

type FetchStaffsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchStaffs(ctx context.Context, arg FetchStaffsParams) ([]Staff, error) {
	rows, err := q.db.Query(ctx, fetchStaffs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.StaffID,
			&i.FirstName,
			&i.LastName,
			&i.AddressID,
			&i.Email,
			&i.StoreID,
			&i.Active,
			&i.Username,
			&i.Password,
			&i.LastUpdate,
			&i.Picture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaff = `-- name: GetStaff :one
SELECT
    staff_id, first_name, last_name, address_id, email, store_id, active, username, password, last_update, picture
FROM
    staff
WHERE staff_id = $1
LIMIT 1
`

func (q *Queries) GetStaff(ctx context.Context, staffID int32) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaff, staffID)
	var i Staff
	err := row.Scan(
		&i.StaffID,
		&i.FirstName,
		&i.LastName,
		&i.AddressID,
		&i.Email,
		&i.StoreID,
		&i.Active,
		&i.Username,
		&i.Password,
		&i.LastUpdate,
		&i.Picture,
	)
	return i, err
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE 
    staff
SET
    first_name = $2,
    last_name = $3,
    email = $4,
    address_id = $5,
    store_id = $6,
    active = $7,
    username = $8,
    password = $9,
    picture = $10,
    last_update = NOW()
WHERE staff_id = $1
RETURNING staff_id, first_name, last_name, address_id, email, store_id, active, username, password, last_update, picture
`

type UpdateStaffParams struct {
	StaffID   int32       `json:"staff_id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     pgtype.Text `json:"email"`
	AddressID int16       `json:"address_id"`
	StoreID   int16       `json:"store_id"`
	Active    bool        `json:"active"`
	Username  string      `json:"username"`
	Password  pgtype.Text `json:"password"`
	Picture   []byte      `json:"picture"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.StaffID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AddressID,
		arg.StoreID,
		arg.Active,
		arg.Username,
		arg.Password,
		arg.Picture,
	)
	var i Staff
	err := row.Scan(
		&i.StaffID,
		&i.FirstName,
		&i.LastName,
		&i.AddressID,
		&i.Email,
		&i.StoreID,
		&i.Active,
		&i.Username,
		&i.Password,
		&i.LastUpdate,
		&i.Picture,
	)
	return i, err
}

const updateStaffPartial = `-- name: UpdateStaffPartial :one
UPDATE 
    staff
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    email = COALESCE($3, email),
    address_id = COALESCE($4, address_id),
    store_id = COALESCE($5, store_id),
    active = COALESCE($6, active),
    username = COALESCE($7, username),
    password = COALESCE($8, password),
    picture = COALESCE($9, picture),
    last_update = NOW()
WHERE staff_id = $10
RETURNING staff_id, first_name, last_name, address_id, email, store_id, active, username, password, last_update, picture
`

type UpdateStaffPartialParams struct {
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     pgtype.Text `json:"email"`
	AddressID pgtype.Int2 `json:"address_id"`
	StoreID   pgtype.Int2 `json:"store_id"`
	Active    pgtype.Bool `json:"active"`
	Username  pgtype.Text `json:"username"`
	Password  pgtype.Text `json:"password"`
	Picture   []byte      `json:"picture"`
	StaffID   int32       `json:"staff_id"`
}

func (q *Queries) UpdateStaffPartial(ctx context.Context, arg UpdateStaffPartialParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaffPartial,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AddressID,
		arg.StoreID,
		arg.Active,
		arg.Username,
		arg.Password,
		arg.Picture,
		arg.StaffID,
	)
	var i Staff
	err := row.Scan(
		&i.StaffID,
		&i.FirstName,
		&i.LastName,
		&i.AddressID,
		&i.Email,
		&i.StoreID,
		&i.Active,
		&i.Username,
		&i.Password,
		&i.LastUpdate,
		&i.Picture,
	)
	return i, err
}
