// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStores = `-- name: CountStores :one
SELECT
    COUNT(*)
FROM
    store
`

func (q *Queries) CountStores(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO
    store
(
    manager_staff_id,
    address_id,
    last_update
)
VALUES
(
    $1,
    $2,
    NOW()
)
RETURNING store_id, manager_staff_id, address_id, last_update
`

type CreateStoreParams struct {
	ManagerStaffID int16 `json:"manager_staff_id"`
	AddressID      int16 `json:"address_id"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.ManagerStaffID, arg.AddressID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.ManagerStaffID,
		&i.AddressID,
		&i.LastUpdate,
	)
	return i, err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM 
    store
WHERE store_id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, storeID int32) error {
	_, err := q.db.Exec(ctx, deleteStore, storeID)
	return err
}

const fetchStoreCustomers = `-- name: FetchStoreCustomers :many
SELECT
    customer.customer_id, customer.store_id, customer.first_name, customer.last_name, customer.email, customer.address_id, customer.activebool, customer.create_date, customer.last_update, customer.active
FROM
    customer
WHERE
    customer.store_id = $1
ORDER BY store_id ASC
LIMIT $2
OFFSET $3
`

type FetchStoreCustomersParams struct {
	StoreID int16 `json:"store_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) FetchStoreCustomers(ctx context.Context, arg FetchStoreCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, fetchStoreCustomers, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustomerID,
			&i.StoreID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AddressID,
			&i.Activebool,
			&i.CreateDate,
			&i.LastUpdate,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchStoreInventory = `-- name: FetchStoreInventory :many
SELECT
    inventory.inventory_id, inventory.film_id, inventory.store_id, inventory.last_update
FROM
    inventory
WHERE
    inventory.store_id = $1
ORDER BY store_id ASC
LIMIT $2
OFFSET $3
`

type FetchStoreInventoryParams struct {
	StoreID int16 `json:"store_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) FetchStoreInventory(ctx context.Context, arg FetchStoreInventoryParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, fetchStoreInventory, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.InventoryID,
			&i.FilmID,
			&i.StoreID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchStores = `-- name: FetchStores :many
SELECT
    store_id, manager_staff_id, address_id, last_update
FROM 
    store
LIMIT $1
OFFSET $2
`

type FetchStoresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchStores(ctx context.Context, arg FetchStoresParams) ([]Store, error) {
	rows, err := q.db.Query(ctx, fetchStores, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.StoreID,
			&i.ManagerStaffID,
			&i.AddressID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStore = `-- name: GetStore :one
SELECT
    store_id, manager_staff_id, address_id, last_update
FROM 
    store
WHERE store_id = $1
LIMIT 1
`

func (q *Queries) GetStore(ctx context.Context, storeID int32) (Store, error) {
	row := q.db.QueryRow(ctx, getStore, storeID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.ManagerStaffID,
		&i.AddressID,
		&i.LastUpdate,
	)
	return i, err
}

const updateStore = `-- name: UpdateStore :one
UPDATE
    store
SET
    manager_staff_id = $2,
    address_id = $3
WHERE store_id = $1
RETURNING store_id, manager_staff_id, address_id, last_update
`

type UpdateStoreParams struct {
	StoreID        int32 `json:"store_id"`
	ManagerStaffID int16 `json:"manager_staff_id"`
	AddressID      int16 `json:"address_id"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore, arg.StoreID, arg.ManagerStaffID, arg.AddressID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.ManagerStaffID,
		&i.AddressID,
		&i.LastUpdate,
	)
	return i, err
}

const updateStorePartial = `-- name: UpdateStorePartial :one
UPDATE
    store
SET
    manager_staff_id = COALESCE($1, manager_staff_id),
    address_id = COALESCE($2, address_id)
WHERE store_id = $3
RETURNING store_id, manager_staff_id, address_id, last_update
`

type UpdateStorePartialParams struct {
	ManagerStaffID pgtype.Int2 `json:"manager_staff_id"`
	AddressID      pgtype.Int2 `json:"address_id"`
	StoreID        int32       `json:"store_id"`
}

func (q *Queries) UpdateStorePartial(ctx context.Context, arg UpdateStorePartialParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStorePartial, arg.ManagerStaffID, arg.AddressID, arg.StoreID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.ManagerStaffID,
		&i.AddressID,
		&i.LastUpdate,
	)
	return i, err
}
