// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actor.sql

package repo

import (
	"context"
)

const countActors = `-- name: CountActors :one
SELECT
    COUNT(*)
FROM
    actor
`

func (q *Queries) CountActors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActor = `-- name: CreateActor :one
INSERT INTO
    actor
(first_name, last_name, last_update)
VALUES
($1, $2, NOW())
RETURNING actor_id, first_name, last_name, last_update
`

type CreateActorParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error) {
	row := q.db.QueryRow(ctx, createActor, arg.FirstName, arg.LastName)
	var i Actor
	err := row.Scan(
		&i.ActorID,
		&i.FirstName,
		&i.LastName,
		&i.LastUpdate,
	)
	return i, err
}

const deleteActor = `-- name: DeleteActor :exec
DELETE FROM 
    actor
WHERE actor_id = $1
`

func (q *Queries) DeleteActor(ctx context.Context, actorID int32) error {
	_, err := q.db.Exec(ctx, deleteActor, actorID)
	return err
}

const fetchActors = `-- name: FetchActors :many
SELECT
    actor_id, first_name, last_name, last_update
FROM 
    actor
LIMIT $1
OFFSET $2
`

type FetchActorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchActors(ctx context.Context, arg FetchActorsParams) ([]Actor, error) {
	rows, err := q.db.Query(ctx, fetchActors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ActorID,
			&i.FirstName,
			&i.LastName,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActor = `-- name: GetActor :one
SELECT
    actor_id, first_name, last_name, last_update
FROM 
    actor
WHERE actor_id = $1
LIMIT 1
`

func (q *Queries) GetActor(ctx context.Context, actorID int32) (Actor, error) {
	row := q.db.QueryRow(ctx, getActor, actorID)
	var i Actor
	err := row.Scan(
		&i.ActorID,
		&i.FirstName,
		&i.LastName,
		&i.LastUpdate,
	)
	return i, err
}

const updateActor = `-- name: UpdateActor :one
UPDATE 
    actor
SET 
    first_name = $2,
    last_name = $3
WHERE actor_id = $1
RETURNING actor_id, first_name, last_name, last_update
`

type UpdateActorParams struct {
	ActorID   int32  `json:"actor_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) UpdateActor(ctx context.Context, arg UpdateActorParams) (Actor, error) {
	row := q.db.QueryRow(ctx, updateActor, arg.ActorID, arg.FirstName, arg.LastName)
	var i Actor
	err := row.Scan(
		&i.ActorID,
		&i.FirstName,
		&i.LastName,
		&i.LastUpdate,
	)
	return i, err
}

const updateActorPartial = `-- name: UpdateActorPartial :one
UPDATE
    actor
SET
    first_name = COLEASE($1, first_name),
    last_name = COLEASE($2, last_name)
WHERE actor_id = $3
RETURNING actor_id, first_name, last_name, last_update
`

type UpdateActorPartialParams struct {
	FirstName interface{} `json:"first_name"`
	LastName  interface{} `json:"last_name"`
	ActorID   int32       `json:"actor_id"`
}

func (q *Queries) UpdateActorPartial(ctx context.Context, arg UpdateActorPartialParams) (Actor, error) {
	row := q.db.QueryRow(ctx, updateActorPartial, arg.FirstName, arg.LastName, arg.ActorID)
	var i Actor
	err := row.Scan(
		&i.ActorID,
		&i.FirstName,
		&i.LastName,
		&i.LastUpdate,
	)
	return i, err
}
