// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country.sql

package repo

import (
	"context"
)

const countCountries = `-- name: CountCountries :one
SELECT
    COUNT(*)
FROM
    country
`

func (q *Queries) CountCountries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCountries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO
    country
(country, last_update)
VALUES
($1, NOW())
RETURNING country_id, country, last_update
`

func (q *Queries) CreateCountry(ctx context.Context, country string) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry, country)
	var i Country
	err := row.Scan(&i.CountryID, &i.Country, &i.LastUpdate)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM 
    country
WHERE country_id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, countryID int32) error {
	_, err := q.db.Exec(ctx, deleteCountry, countryID)
	return err
}

const fetchCountries = `-- name: FetchCountries :many
SELECT
    country_id, country, last_update
FROM 
    country
LIMIT $1
OFFSET $2
`

type FetchCountriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchCountries(ctx context.Context, arg FetchCountriesParams) ([]Country, error) {
	rows, err := q.db.Query(ctx, fetchCountries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.CountryID, &i.Country, &i.LastUpdate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountry = `-- name: GetCountry :one
SELECT
    country_id, country, last_update
FROM 
    country
WHERE country_id = $1
LIMIT 1
`

func (q *Queries) GetCountry(ctx context.Context, countryID int32) (Country, error) {
	row := q.db.QueryRow(ctx, getCountry, countryID)
	var i Country
	err := row.Scan(&i.CountryID, &i.Country, &i.LastUpdate)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE 
    country
SET 
    country = $2
WHERE country_id = $1
RETURNING country_id, country, last_update
`

type UpdateCountryParams struct {
	CountryID int32  `json:"country_id"`
	Country   string `json:"country"`
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, updateCountry, arg.CountryID, arg.Country)
	var i Country
	err := row.Scan(&i.CountryID, &i.Country, &i.LastUpdate)
	return i, err
}
