// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: film.sql

package repo

import (
	"context"
)

const countFilms = `-- name: CountFilms :one
SELECT
    COUNT(*)
FROM
    film
`

func (q *Queries) CountFilms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFilms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fetchFilmActors = `-- name: FetchFilmActors :many
SELECT
    actor.actor_id, actor.first_name, actor.last_name, actor.last_update
FROM 
    actor
JOIN 
    film_actor 
    ON
    film_actor.actor_id = actor.actor_id
WHERE 
    film_actor.film_id = $1
ORDER BY first_name ASC
LIMIT $2
OFFSET $3
`

type FetchFilmActorsParams struct {
	FilmID int16 `json:"film_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchFilmActors(ctx context.Context, arg FetchFilmActorsParams) ([]Actor, error) {
	rows, err := q.db.Query(ctx, fetchFilmActors, arg.FilmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ActorID,
			&i.FirstName,
			&i.LastName,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchFilms = `-- name: FetchFilms :many
SELECT
    film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext
FROM 
    film
LIMIT $1
OFFSET $2
`

type FetchFilmsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchFilms(ctx context.Context, arg FetchFilmsParams) ([]Film, error) {
	rows, err := q.db.Query(ctx, fetchFilms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Film
	for rows.Next() {
		var i Film
		if err := rows.Scan(
			&i.FilmID,
			&i.Title,
			&i.Description,
			&i.ReleaseYear,
			&i.LanguageID,
			&i.RentalDuration,
			&i.RentalRate,
			&i.Length,
			&i.ReplacementCost,
			&i.Rating,
			&i.LastUpdate,
			&i.SpecialFeatures,
			&i.Fulltext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilm = `-- name: GetFilm :one
SELECT
    film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext
FROM 
    film
WHERE film_id = $1
LIMIT 1
`

func (q *Queries) GetFilm(ctx context.Context, filmID int32) (Film, error) {
	row := q.db.QueryRow(ctx, getFilm, filmID)
	var i Film
	err := row.Scan(
		&i.FilmID,
		&i.Title,
		&i.Description,
		&i.ReleaseYear,
		&i.LanguageID,
		&i.RentalDuration,
		&i.RentalRate,
		&i.Length,
		&i.ReplacementCost,
		&i.Rating,
		&i.LastUpdate,
		&i.SpecialFeatures,
		&i.Fulltext,
	)
	return i, err
}
