// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: language.sql

package repo

import (
	"context"
)

const countLanguages = `-- name: CountLanguages :one
SELECT
    COUNT(*)
FROM
    language
`

func (q *Queries) CountLanguages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLanguages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fetchLanguages = `-- name: FetchLanguages :many
SELECT
    language_id, name, last_update
FROM 
    language
ORDER BY name ASC
LIMIT $1
OFFSET $2
`

type FetchLanguagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FetchLanguages(ctx context.Context, arg FetchLanguagesParams) ([]Language, error) {
	rows, err := q.db.Query(ctx, fetchLanguages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.LanguageID, &i.Name, &i.LastUpdate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLanguage = `-- name: GetLanguage :one
SELECT
    language_id, name, last_update
FROM 
    language
WHERE language_id = $1
LIMIT 1
`

func (q *Queries) GetLanguage(ctx context.Context, languageID int32) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguage, languageID)
	var i Language
	err := row.Scan(&i.LanguageID, &i.Name, &i.LastUpdate)
	return i, err
}
