// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MpaaRating string

const (
	MpaaRatingG    MpaaRating = "G"
	MpaaRatingPG   MpaaRating = "PG"
	MpaaRatingPG13 MpaaRating = "PG-13"
	MpaaRatingR    MpaaRating = "R"
	MpaaRatingNC17 MpaaRating = "NC-17"
)

func (e *MpaaRating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MpaaRating(s)
	case string:
		*e = MpaaRating(s)
	default:
		return fmt.Errorf("unsupported scan type for MpaaRating: %T", src)
	}
	return nil
}

type NullMpaaRating struct {
	MpaaRating MpaaRating `json:"mpaa_rating"`
	Valid      bool       `json:"valid"` // Valid is true if MpaaRating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMpaaRating) Scan(value interface{}) error {
	if value == nil {
		ns.MpaaRating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MpaaRating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMpaaRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MpaaRating), nil
}

type Actor struct {
	ActorID    int32            `json:"actor_id"`
	FirstName  string           `json:"first_name"`
	LastName   string           `json:"last_name"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type ActorInfo struct {
	ActorID   int32       `json:"actor_id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	FilmInfo  interface{} `json:"film_info"`
}

type Address struct {
	AddressID  int32            `json:"address_id"`
	Address    string           `json:"address"`
	Address2   pgtype.Text      `json:"address2"`
	District   string           `json:"district"`
	CityID     int16            `json:"city_id"`
	PostalCode pgtype.Text      `json:"postal_code"`
	Phone      string           `json:"phone"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type Category struct {
	CategoryID int32            `json:"category_id"`
	Name       string           `json:"name"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type City struct {
	CityID     int32            `json:"city_id"`
	City       string           `json:"city"`
	CountryID  int16            `json:"country_id"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type Country struct {
	CountryID  int32            `json:"country_id"`
	Country    string           `json:"country"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type Customer struct {
	CustomerID int32            `json:"customer_id"`
	StoreID    int16            `json:"store_id"`
	FirstName  string           `json:"first_name"`
	LastName   string           `json:"last_name"`
	Email      pgtype.Text      `json:"email"`
	AddressID  int16            `json:"address_id"`
	Activebool bool             `json:"activebool"`
	CreateDate pgtype.Date      `json:"create_date"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
	Active     pgtype.Int4      `json:"active"`
}

type CustomerList struct {
	ID      int32       `json:"id"`
	Name    interface{} `json:"name"`
	Address string      `json:"address"`
	ZipCode pgtype.Text `json:"zip code"`
	Phone   string      `json:"phone"`
	City    string      `json:"city"`
	Country string      `json:"country"`
	Notes   string      `json:"notes"`
	Sid     int16       `json:"sid"`
}

type Film struct {
	FilmID          int32            `json:"film_id"`
	Title           string           `json:"title"`
	Description     pgtype.Text      `json:"description"`
	ReleaseYear     interface{}      `json:"release_year"`
	LanguageID      int16            `json:"language_id"`
	RentalDuration  int16            `json:"rental_duration"`
	RentalRate      pgtype.Numeric   `json:"rental_rate"`
	Length          pgtype.Int2      `json:"length"`
	ReplacementCost pgtype.Numeric   `json:"replacement_cost"`
	Rating          NullMpaaRating   `json:"rating"`
	LastUpdate      pgtype.Timestamp `json:"last_update"`
	SpecialFeatures []string         `json:"special_features"`
	Fulltext        interface{}      `json:"fulltext"`
}

type FilmActor struct {
	ActorID    int16            `json:"actor_id"`
	FilmID     int16            `json:"film_id"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type FilmCategory struct {
	FilmID     int16            `json:"film_id"`
	CategoryID int16            `json:"category_id"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type FilmList struct {
	Fid         pgtype.Int4    `json:"fid"`
	Title       pgtype.Text    `json:"title"`
	Description pgtype.Text    `json:"description"`
	Category    string         `json:"category"`
	Price       pgtype.Numeric `json:"price"`
	Length      pgtype.Int2    `json:"length"`
	Rating      NullMpaaRating `json:"rating"`
	Actors      interface{}    `json:"actors"`
}

type Inventory struct {
	InventoryID int32            `json:"inventory_id"`
	FilmID      int16            `json:"film_id"`
	StoreID     int16            `json:"store_id"`
	LastUpdate  pgtype.Timestamp `json:"last_update"`
}

type Language struct {
	LanguageID int32            `json:"language_id"`
	Name       string           `json:"name"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
}

type NicerButSlowerFilmList struct {
	Fid         pgtype.Int4    `json:"fid"`
	Title       pgtype.Text    `json:"title"`
	Description pgtype.Text    `json:"description"`
	Category    string         `json:"category"`
	Price       pgtype.Numeric `json:"price"`
	Length      pgtype.Int2    `json:"length"`
	Rating      NullMpaaRating `json:"rating"`
	Actors      interface{}    `json:"actors"`
}

type Payment struct {
	PaymentID   int32            `json:"payment_id"`
	CustomerID  int16            `json:"customer_id"`
	StaffID     int16            `json:"staff_id"`
	RentalID    int32            `json:"rental_id"`
	Amount      pgtype.Numeric   `json:"amount"`
	PaymentDate pgtype.Timestamp `json:"payment_date"`
}

type Rental struct {
	RentalID    int32            `json:"rental_id"`
	RentalDate  pgtype.Timestamp `json:"rental_date"`
	InventoryID int32            `json:"inventory_id"`
	CustomerID  int16            `json:"customer_id"`
	ReturnDate  pgtype.Timestamp `json:"return_date"`
	StaffID     int16            `json:"staff_id"`
	LastUpdate  pgtype.Timestamp `json:"last_update"`
}

type SalesByFilmCategory struct {
	Category   string `json:"category"`
	TotalSales int64  `json:"total_sales"`
}

type SalesByStore struct {
	Store      interface{} `json:"store"`
	Manager    interface{} `json:"manager"`
	TotalSales int64       `json:"total_sales"`
}

type Staff struct {
	StaffID    int32            `json:"staff_id"`
	FirstName  string           `json:"first_name"`
	LastName   string           `json:"last_name"`
	AddressID  int16            `json:"address_id"`
	Email      pgtype.Text      `json:"email"`
	StoreID    int16            `json:"store_id"`
	Active     bool             `json:"active"`
	Username   string           `json:"username"`
	Password   pgtype.Text      `json:"password"`
	LastUpdate pgtype.Timestamp `json:"last_update"`
	Picture    []byte           `json:"picture"`
}

type StaffList struct {
	ID      int32       `json:"id"`
	Name    interface{} `json:"name"`
	Address string      `json:"address"`
	ZipCode pgtype.Text `json:"zip code"`
	Phone   string      `json:"phone"`
	City    string      `json:"city"`
	Country string      `json:"country"`
	Sid     int16       `json:"sid"`
}

type Store struct {
	StoreID        int32            `json:"store_id"`
	ManagerStaffID int16            `json:"manager_staff_id"`
	AddressID      int16            `json:"address_id"`
	LastUpdate     pgtype.Timestamp `json:"last_update"`
}
