// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CountActors(ctx context.Context) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountCities(ctx context.Context) (int64, error)
	CountCountries(ctx context.Context) (int64, error)
	CountFilms(ctx context.Context) (int64, error)
	CountLanguages(ctx context.Context) (int64, error)
	CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	CreateCountry(ctx context.Context, country string) (Country, error)
	DeleteActor(ctx context.Context, actorID int32) error
	DeleteCategory(ctx context.Context, categoryID int32) error
	DeleteCity(ctx context.Context, cityID int32) error
	DeleteCountry(ctx context.Context, countryID int32) error
	FetchActorFilms(ctx context.Context, arg FetchActorFilmsParams) ([]Film, error)
	FetchActors(ctx context.Context, arg FetchActorsParams) ([]Actor, error)
	FetchCategories(ctx context.Context, arg FetchCategoriesParams) ([]Category, error)
	FetchCategoryFilms(ctx context.Context, arg FetchCategoryFilmsParams) ([]Film, error)
	FetchCities(ctx context.Context, arg FetchCitiesParams) ([]City, error)
	FetchCountries(ctx context.Context, arg FetchCountriesParams) ([]Country, error)
	FetchFilmActors(ctx context.Context, arg FetchFilmActorsParams) ([]Actor, error)
	FetchFilmCategories(ctx context.Context, arg FetchFilmCategoriesParams) ([]Category, error)
	FetchFilms(ctx context.Context, arg FetchFilmsParams) ([]Film, error)
	FetchLanguages(ctx context.Context, arg FetchLanguagesParams) ([]Language, error)
	GetActor(ctx context.Context, actorID int32) (Actor, error)
	GetCategory(ctx context.Context, categoryID int32) (Category, error)
	GetCity(ctx context.Context, cityID int32) (City, error)
	GetCountry(ctx context.Context, countryID int32) (Country, error)
	GetFilm(ctx context.Context, filmID int32) (Film, error)
	GetLanguage(ctx context.Context, languageID int32) (Language, error)
	UpdateActor(ctx context.Context, arg UpdateActorParams) (Actor, error)
	UpdateActorPartial(ctx context.Context, arg UpdateActorPartialParams) (Actor, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryPartial(ctx context.Context, arg UpdateCategoryPartialParams) (Category, error)
	UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error)
	UpdateCityPartial(ctx context.Context, arg UpdateCityPartialParams) (City, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
}

var _ Querier = (*Queries)(nil)
