// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CountActors(ctx context.Context) (int64, error)
	CountFilms(ctx context.Context) (int64, error)
	FetchActors(ctx context.Context, arg FetchActorsParams) ([]Actor, error)
	FetchFilms(ctx context.Context, arg FetchFilmsParams) ([]Film, error)
}

var _ Querier = (*Queries)(nil)
