global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['192.168.18.167:18000']

  - job_name: 'auth-svc'
    static_configs:
      - targets: ['192.168.18.167:18001']
  - job_name: 'users-svc'
    static_configs:
      - targets: ['192.168.18.167:18002']
  - job_name: 'notes-svc'
    static_configs:
      - targets: ['192.168.18.167:18003']
